//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElementLab.Drugscreening {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Monograph {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Monograph() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElementLab.Drugscreening.Monograph", typeof(Monograph).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        internal static string alerttitle {
            get {
                return ResourceManager.GetString("alerttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breast Feeding Aaps.
        /// </summary>
        internal static string breastfeedingaapstitle {
            get {
                return ResourceManager.GetString("breastfeedingaapstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breast Feeding Excreteds.
        /// </summary>
        internal static string breastfeedingexcretedstitle {
            get {
                return ResourceManager.GetString("breastfeedingexcretedstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breast Feeding Ratings.
        /// </summary>
        internal static string breastfeedingratingstitle {
            get {
                return ResourceManager.GetString("breastfeedingratingstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примечания.
        /// </summary>
        internal static string commenttitle {
            get {
                return ResourceManager.GetString("commenttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обсуждение.
        /// </summary>
        internal static string discussiontitle {
            get {
                return ResourceManager.GetString("discussiontitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доказанность.
        /// </summary>
        internal static string documentationlevelstitle {
            get {
                return ResourceManager.GetString("documentationlevelstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string documentuniqueid {
            get {
                return ResourceManager.GetString("documentuniqueid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Препараты.
        /// </summary>
        internal static string drugstitle {
            get {
                return ResourceManager.GetString("drugstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эффект.
        /// </summary>
        internal static string effecttitle {
            get {
                return ResourceManager.GetString("effecttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкции.
        /// </summary>
        internal static string instructionstitle {
            get {
                return ResourceManager.GetString("instructionstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        internal static string managementlevelstitle {
            get {
                return ResourceManager.GetString("managementlevelstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        internal static string managementtitle {
            get {
                return ResourceManager.GetString("managementtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Механизм.
        /// </summary>
        internal static string mechanismtitle {
            get {
                return ResourceManager.GetString("mechanismtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость.
        /// </summary>
        internal static string onsetstitle {
            get {
                return ResourceManager.GetString("onsetstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placental Transfers.
        /// </summary>
        internal static string placentaltransferstitle {
            get {
                return ResourceManager.GetString("placentaltransferstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Источники.
        /// </summary>
        internal static string referencestitle {
            get {
                return ResourceManager.GetString("referencestitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серьезность.
        /// </summary>
        internal static string severitylevelstitle {
            get {
                return ResourceManager.GetString("severitylevelstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&apos;html&apos; version=&apos;1.0&apos; encoding=&apos;UTF-8&apos; indent=&apos;yes&apos; /&gt;
        ///  &lt;xsl:param name=&quot;documentuniqueid&quot;&gt;&lt;/xsl:param&gt;
        ///  &lt;xsl:param name=&quot;managementlevelstitle&quot;&gt;&lt;/xsl:param&gt;
        ///  &lt;xsl:param name=&quot;severitylevelstitle&quot;&gt;&lt;/xsl:param&gt;
        ///  &lt;xsl:param name=&quot;documentationlevelstitle&quot;&gt;&lt;/xsl:param&gt;
        ///  &lt;xsl:param name=&quot;onsetstitle&quot;&gt;&lt;/xsl:param&gt;
        ///  &lt;xsl:param name=&quot;placentaltransferstitle&quot;&gt;&lt;/xsl:param&gt;
        ///  &lt;xsl:param name=&quot;breastfeedin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stylesheet {
            get {
                return ResourceManager.GetString("Stylesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Признаки.
        /// </summary>
        internal static string whattitle {
            get {
                return ResourceManager.GetString("whattitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причины.
        /// </summary>
        internal static string whytitle {
            get {
                return ResourceManager.GetString("whytitle", resourceCulture);
            }
        }
    }
}
