//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElementLab.Drugscreening.Client.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElementLab.Drugscreening.Client.Tests.TestResponses", typeof(TestResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ClientId&quot;:&quot;TestUser&quot;,&quot;Token&quot;:&quot;TestToken&quot;}.
        /// </summary>
        internal static string AccountToken {
            get {
                return ResourceManager.GetString("AccountToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Id&quot;:&quot;a728d5e3-9def-4d9e-98ed-1e9f43ddbd98&quot;,&quot;Messages&quot;:[],&quot;DrugDrugInteractions&quot;:{&quot;Items&quot;:[{&quot;PatientAlert&quot;:&quot;Одновременный прием препаратов \&quot;Варфарекс табл. 3мг\&quot; и \&quot;Аспирин табл. 500мг\&quot; увеличивает способность препарата \&quot;Варфарекс табл. 3мг\&quot; разжижать кровь. Повышается риск развития сильного кровотечения и появления выраженных кровоподтеков. Данный риск связан с дозировкой  препарата \&quot;Аспирин табл. 500мг\&quot;. Время от времени можно намеренно назначать препарат \&quot;Аспирин табл. 500мг\&quot; в небольших дозах  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllScreenings {
            get {
                return ResourceManager.GetString("AllScreenings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UniqueId&quot;: 660,
        ///        &quot;ResourceUrl&quot;: &quot;http://localhost/concepts/dispensabledrug?code=DD0000800&quot;,
        ///        &quot;ExtendedProperties&quot;: {
        ///            &quot;DrugForm&quot;: {
        ///                &quot;Code&quot;: &quot;DF097&quot;,
        ///                &quot;Name&quot;: &quot;таблетки&quot;
        ///            },
        ///            &quot;Regions&quot;: [
        ///                &quot;RU&quot;
        ///            ]
        ///        },
        ///        &quot;Type&quot;: &quot;DispensableDrug&quot;,
        ///        &quot;Code&quot;: &quot;DD0000800&quot;,
        ///        &quot;Name&quot;: &quot;Аспирин табл. 100мг&quot;
        ///    }.
        /// </summary>
        internal static string AspirinConcept {
            get {
                return ResourceManager.GetString("AspirinConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;DisplayName&quot;: &quot;Аспирин табл. 100мг&quot;,
        ///        &quot;Score&quot;: 105,
        ///        &quot;UniqueId&quot;: 660,
        ///        &quot;ResourceUrl&quot;: &quot;http://localhost/concepts/dispensabledrug?code=DD0000800&quot;,
        ///        &quot;ExtendedProperties&quot;: {
        ///            &quot;DrugForm&quot;: {
        ///                &quot;Code&quot;: &quot;DF097&quot;,
        ///                &quot;Name&quot;: &quot;таблетки&quot;
        ///            },
        ///            &quot;Regions&quot;: [
        ///                &quot;RU&quot;
        ///            ]
        ///        },
        ///        &quot;Type&quot;: &quot;DispensableDrug&quot;,
        ///        &quot;Code&quot;: &quot;DD0000800&quot;,
        ///        &quot;Name&quot;: &quot;Аспирин табл. 100мг&quot;
        ///    }].
        /// </summary>
        internal static string FindAspirinByScope {
            get {
                return ResourceManager.GetString("FindAspirinByScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Code&quot;: &quot;a32d6a19-a1c6-47fd-ad95-1a6e58e92212&quot;,
        ///    &quot;Name&quot;: &quot;Варфарин, таблетки по 2,5 мг. ОЗОН, ООО (Россия)&quot;,
        ///    &quot;ResourceUrl&quot;: &quot;http://localhost/instructions/a32d6a19-a1c6-47fd-ad95-1a6e58e92212&quot;,
        ///    &quot;Content&quot;: &quot;&lt;Drug&gt;&lt;/Drug&gt;&quot;
        ///}.
        /// </summary>
        internal static string Instruction_a32d6a19a1c647fdad951a6e58e92212 {
            get {
                return ResourceManager.GetString("Instruction_a32d6a19a1c647fdad951a6e58e92212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Drug&gt;&lt;Alerts&gt;&lt;Alert type=&quot;AgeAbove60&quot; severity=&quot;3&quot; details=&quot;WithCare&quot; /&gt;&lt;Alert type=&quot;HepaticDisease&quot; severity=&quot;3&quot; details=&quot;WithCare&quot; /&gt;&lt;Alert type=&quot;KidneyDisease&quot; severity=&quot;3&quot; details=&quot;WithCare&quot; /&gt;&lt;Alert type=&quot;Pregnancy&quot; severity=&quot;3&quot; details=&quot;WithCare&quot; /&gt;&lt;Alert type=&quot;Diabetes&quot; severity=&quot;1&quot; details=&quot;CounterIndications&quot; /&gt;&lt;/Alerts&gt;&lt;TradeName locale=&quot;Ru&quot; value=&quot;Варфарин&quot; /&gt;&lt;TradeName locale=&quot;En&quot; value=&quot;Warfarin&quot; /&gt;&lt;Mnn value=&quot;Варфарин&quot; /&gt;&lt;RegistrationDate value=&quot;18.08.2010&quot; /&gt;&lt;HtmlSection name=&quot;RegistrationNu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstructionContent_a32d6a19a1c647fdad951a6e58e92212 {
            get {
                return ResourceManager.GetString("InstructionContent_a32d6a19a1c647fdad951a6e58e92212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Code&quot;:&quot;a32d6a19-a1c6-47fd-ad95-1a6e58e92212&quot;,&quot;Name&quot;:&quot;Варфарин, таблетки по 2,5 мг. ОЗОН, ООО (Россия)&quot;,&quot;ContentUrl&quot;:&quot;http://localhost/instructions/a32d6a19-a1c6-47fd-ad95-1a6e58e92212&quot;},{&quot;Code&quot;:&quot;c3363969-50c4-4631-9611-acf6adafa139&quot;,&quot;Name&quot;:&quot;Варфарин, таблетки по 2,50 мг. КАНОНФАРМА ПРОДАКШН, ЗАО (Россия)&quot;,&quot;ContentUrl&quot;:&quot;http://localhost/instructions/c3363969-50c4-4631-9611-acf6adafa139&quot;}].
        /// </summary>
        internal static string InstructionsForWarfarin {
            get {
                return ResourceManager.GetString("InstructionsForWarfarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;UniqueId&quot;: 123,
        ///        &quot;ResourceUrl&quot;: &quot;http://localhost/concepts/type1?code=TST123&quot;,
        /// 
        ///        &quot;Type&quot;: &quot;Type1&quot;,
        ///        &quot;Code&quot;: &quot;TST123&quot;,
        ///        &quot;Name&quot;: &quot;Концепт1&quot;
        ///    }].
        /// </summary>
        internal static string ListConcepts {
            get {
                return ResourceManager.GetString("ListConcepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Type&quot;: &quot;Type1&quot;,&quot;Name&quot;: &quot;Название1&quot;},{&quot;Type&quot;: &quot;Type2&quot;,&quot;Name&quot;: &quot;Название2&quot;}].
        /// </summary>
        internal static string ListConceptTypes {
            get {
                return ResourceManager.GetString("ListConceptTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Message&quot;: &quot;Не удалось найти DispensableDrug с указанным кодом&quot;
        ///}.
        /// </summary>
        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SimpleMonographHtml {
            get {
                return ResourceManager.GetString("SimpleMonographHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;monograph&gt;&lt;title&gt;&lt;para&gt;Боластерон&lt;/para&gt;&lt;/title&gt;&lt;alert&gt;&lt;para&gt;Субстанция &quot;Боластерон&quot; включена в запрещенный список WADA (класс S1.1.a).&lt;/para&gt;&lt;/alert&gt;&lt;comment&gt;&lt;para&gt;Субстанция &quot;Боластерон&quot; запрещена к приему всем спортсменам в соревновательный и во внесоревновательный периоды во всех видах спорта.&lt;/para&gt;&lt;/comment&gt;&lt;disclaimer&gt;&lt;para&gt;Информация, предоставляемая Сервисом, предназначена для медицинских и фармацевтических работников, а также может быть использована в качеств [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleMonographXml {
            get {
                return ResourceManager.GetString("SimpleMonographXml", resourceCulture);
            }
        }
    }
}
